-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Apr 26, 2023 at 02:47 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `locus`
--

-- --------------------------------------------------------

--
-- Table structure for table `tblhouse`
--

CREATE TABLE `tblhouse` (
  `pid` int(100) NOT NULL,
  `uid` int(100) NOT NULL,
  `ptitle` longtext NOT NULL,
  `ptype` varchar(250) NOT NULL,
  `bhk` varchar(100) NOT NULL,
  `stype` varchar(100) NOT NULL,
  `bedroom` int(100) NOT NULL,
  `balcony` int(100) NOT NULL,
  `bathroom` int(100) NOT NULL,
  `kitchen` int(100) NOT NULL,
  `hall` int(100) NOT NULL,
  `floor` int(100) NOT NULL,
  `tfloor` int(100) NOT NULL,
  `price` int(250) NOT NULL,
  `sqft` varchar(250) NOT NULL,
  `paddress` varchar(250) NOT NULL,
  `city` varchar(250) NOT NULL,
  `state` varchar(250) NOT NULL,
  `img1` varchar(250) NOT NULL,
  `img2` varchar(250) NOT NULL,
  `img3` varchar(250) NOT NULL,
  `img4` varchar(250) NOT NULL,
  `ebill` varchar(250) NOT NULL,
  `tbill` varchar(250) NOT NULL,
  `status` enum('Active','Inactive','','') NOT NULL DEFAULT 'Active',
  `featured` longtext NOT NULL,
  `description` text NOT NULL,
  `facilities` longtext NOT NULL,
  `date` timestamp NOT NULL DEFAULT current_timestamp(),
  `qc` enum('Pending','Reject','Success','') NOT NULL DEFAULT 'Pending',
  `response` varchar(255) NOT NULL DEFAULT 'Your Listing Is Live...'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tblhouse`
--

INSERT INTO `tblhouse` (`pid`, `uid`, `ptitle`, `ptype`, `bhk`, `stype`, `bedroom`, `balcony`, `bathroom`, `kitchen`, `hall`, `floor`, `tfloor`, `price`, `sqft`, `paddress`, `city`, `state`, `img1`, `img2`, `img3`, `img4`, `ebill`, `tbill`, `status`, `featured`, `description`, `facilities`, `date`, `qc`, `response`) VALUES
(165, 60, 'Beautifully Designed and Spacious Four-Bedroom House with Stunning Views one', 'House', '4', 'Rent', 4, 3, 5, 1, 1, 2, 2, 29999, '1500', '49 md park socity simada gam  1', 'Surat', 'Gujarat', 'vu-anh-TiVPTYCG_3E-unsplash (1).jpg', 'spacejoy-IARlbQa6Kc8-unsplash.jpg', 'jakob-owens-XKLZia7hPYI-unsplash.jpg', 'alberto-castillo-q-mx4mSkK9zeo-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', '', '<p>Welcome to this stunning 4-bedroom house located in the heart of a quiet and peaceful neighborhood. This beautifully designed home boasts a spacious living room with large windows offering stunning views of the surrounding mountains and natural landscapes.</p>\r\n<p>The open-plan kitchen is fully equipped with high-end appliances and a large island, making it perfect for entertaining guests. The dining area opens up to a private deck, where you can enjoy your morning coffee while taking in the breathtaking views.</p>\r\n<p>All four bedrooms are located on the upper level and are generously sized, offering plenty of natural light and space for your family to grow. The master bedroom has its own ensuite bathroom, walk-in closet, and private balcony overlooking the picturesque scenery.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 11:24:41', 'Success', 'Your Listing Is Live...'),
(167, 60, 'Luxurious Five-Bedroom Penthouse with Stunning City ', 'Pent-House', '5', 'Rent', 5, 6, 6, 1, 2, 3, 3, 69999, '1500', 'A-504 Raghuveer Heights VIP Road Vesu ', 'Surat', 'Gujrat', 'jennifer-r-sZ9F_XkGJfI-unsplash.jpg', 'drew-dau-bWijQI4v0dM-unsplash.jpg', 'lisa-reichenstein-P_FdMYiT7GU-unsplash.jpg', 'r-architecture-TRCJ-87Yoh0-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', '', '<p>Welcome to this luxurious 5-bedroom penthouse located in the heart of the city. As you enter, you will be greeted by a grand foyer that leads into a spacious and elegant living room with floor-to-ceiling windows offering stunning views of the city skyline.</p>\r\n<p>The open-plan kitchen is fully equipped with high-end appliances and features a large island, making it perfect for entertaining guests. The dining area is spacious and offers plenty of room for a large table, perfect for hosting dinner parties.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 11:33:56', 'Success', 'Your Listing Is Live...'),
(168, 60, 'Charming and Cozy Two-Bedroom Cottage with a Beautiful Garden', 'Banglow', '2', 'Sell', 2, 2, 3, 1, 1, 2, 2, 1500000, '1500', 'A-504 Happy Homes Near VR Mall , Vesu ', 'Surat', 'Gujarat', 'brie-odom-mabey-ITzfgP77DTg-unsplash.jpg', 'sidekix-media-NTH9ZZcUih8-unsplash.jpg', 'john-fornander-y3_AHHrxUBY-unsplash (1).jpg', 'lisa-reichenstein-P_FdMYiT7GU-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This charming and cozy 2-bedroom cottage is located in a quiet and peaceful neighborhood and is perfect for those looking for a private retreat. As you enter, you will be greeted by a warm and inviting living room with a wood-burning fireplace, perfect for relaxing on chilly nights.</p>\r\n<p>The kitchen is fully equipped with all the necessary appliances, and the dining area is perfect for enjoying a meal with family and friends. The cottage has two well-appointed bedrooms, both with comfortable beds and plenty of closet space.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 11:54:58', 'Success', 'Your Listing Is Live...'),
(169, 60, 'Spacious and Modern Four-Bedroom Family Home with Large Farm House', 'Farm-House', '5', 'Rent', 3, 2, 4, 1, 1, 2, 2, 3500000, '500', '12 Blue Horizon , Utran Road , Utran', 'Anjar', 'Gujarat', 'john-fornander-tVzyDSV84w8-unsplash.jpg', 'john-fornander-y3_AHHrxUBY-unsplash (1).jpg', 'sidekix-media-RwXneIyqxAw-unsplash.jpg', 'lisa-reichenstein-P_FdMYiT7GU-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', '', '<p>This spacious and modern 4-bedroom home is perfect for families. It features a large living room, an open-plan kitchen with stainless steel appliances, and a dining area that leads out to a huge backyard. The property also includes a two-car garage and is conveniently located near schools and parks.</p>\r\n<p>This spacious and modern 4-bedroom home is perfect for families. It features a large living room, an open-plan kitchen with stainless steel appliances, and a dining area that leads out to a huge backyard. The property also includes a two-car garage and is conveniently located near schools and parks.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:02:02', 'Success', 'Your Listing Is Live...'),
(170, 61, 'Stunning Two-Bedroom Condo with Ocean Views', 'House', '2', 'Rent', 2, 3, 3, 1, 1, 1, 1, 9999, '1859', '99 Nilkanth Dham Soc , Nikol Gam', 'Ahemdabad', 'Gujarat', 'ralph-ravi-kayden-2d4lAQAlbDA-unsplash.jpg', 'kara-eads-L7EwHkq1B2s-unsplash.jpg', 'eric-deschaintre-alSZkWagD54-unsplash.jpg', 'spacejoy-nEtpvJjnPVo-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This stunning 2-bedroom condo is located in a prestigious building with views of the ocean. It features a spacious living room with a fireplace, a gourmet kitchen, and a dining area that leads out to a balcony with breathtaking views. The property also includes a fitness center, a pool, and 24-hour security.</p>\r\n<p>This charming and cozy 1-bedroom apartment is located in the heart of the city. It features a comfortable living room, a well-equipped kitchen, and a bedroom with a queen-sized bed. The property is within walking distance of shops, restaurants, and public transportation.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:11:45', 'Success', 'Your Listing Is Live...'),
(171, 61, 'Modern and Stylish Three-Bedroom Townhome with Rooftop Terrace', 'Banglow', '4', 'Rent', 4, 5, 4, 2, 2, 1, 1, 19999, '345', '101 Ramnath Soc Bapunagar gam ', 'Ahemdabad', 'Gujarat', 'r-architecture-2gDwlIim3Uw-unsplash.jpg', 'dim-hou-h8wLc3lbDuA-unsplash.jpg', 'roberto-nickson-fAa25CyYtrg-unsplash.jpg', 'sidekix-media-VD8kjWCzQyw-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This modern and stylish 3-bedroom townhome features an open-plan living and dining area, a gourmet kitchen with stainless steel appliances, and a rooftop terrace with stunning views. The property also includes a two-car garage and is located in a desirable neighborhood close to schools and parks.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:18:25', 'Success', 'Your Listing Is Live...'),
(172, 61, 'Spectacular Five-Bedroom Mansion with Pool and Tennis Court', 'Pent-House', '5', 'Sell', 6, 5, 5, 2, 2, 1, 1, 9600000, '21500', 'A-504 Raghuveer Heights  Aostral ', 'Ahemdabad', 'Gujarat', 'brie-odom-mabey-ITzfgP77DTg-unsplash.jpg', 'ralph-ravi-kayden-mR1CIDduGLc-unsplash.jpg', 'dim-hou-h8wLc3lbDuA-unsplash.jpg', 'infinite-views-79NjpXDOJU8-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This spectacular 5-bedroom mansion is situated on a sprawling estate with a pool, tennis court, and lush gardens. It features a grand foyer, a formal living room with a fireplace, a gourmet kitchen, and a luxurious master suite with a spa-like bathroom. The property is ideal for those who value privacy and luxury.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:22:49', 'Success', 'Your Listing Is Live...'),
(173, 61, 'Cozy and Inviting two-Bedroom Cabin in the Woods', 'Farm-House', '2', 'Rent', 2, 2, 3, 1, 1, 1, 1, 12999, '1500', '101 ,  Krishna Soc , VIP Road ', 'Ahemdabad', 'Gujarat', 'ralph-ravi-kayden-2d4lAQAlbDA-unsplash.jpg', 'francesca-tosolini-hCU4fimRW-c-unsplash.jpg', 'bernard-hermant-CLKGGwIBTaY-unsplash.jpg', 'infinite-views-79NjpXDOJU8-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This cozy and inviting 2-bedroom cabin is nestled in the woods and is perfect for those who love the outdoors. It features a living room with a wood-burning stove, a kitchen with all the necessary appliances, and a spacious deck for outdoor entertaining. The property is within close proximity to hiking and biking trails.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:27:36', 'Success', 'Your Listing Is Live...'),
(174, 62, ' Elegant and Sophisticated Four-Bedroom Colonial Home with Pool', 'House', '4', 'Rent', 4, 4, 4, 1, 1, 1, 1, 12100, '76544', '49 Tirupati socity simada gam ', 'Vadodara', 'Gujarat', 'lisa-reichenstein-P_FdMYiT7GU-unsplash.jpg', 'roberto-nickson-fAa25CyYtrg-unsplash.jpg', 'point3d-commercial-imaging-ltd-xqlHYzU7WAY-unsplash.jpg', 'infinite-views-79NjpXDOJU8-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This elegant and sophisticated 4-bedroom colonial home is located in a desirable neighborhood and features a formal living room, a family room with a fireplace, a gourmet kitchen, and a stunning pool area. The property also includes a two-car garage and is within close proximity to shopping and dining.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:38:15', 'Success', 'Your Listing Is Live...'),
(175, 62, 'Rustic and Charming three-Bedroom Farmhouse with Acreage', 'House', '3', 'Sell', 3, 3, 4, 1, 1, 1, 1, 2300100, '1200', '49 AB park Soc chopati ', 'Vadodara', 'Gujarat', 'bernard-hermant-CLKGGwIBTaY-unsplash.jpg', 'jakob-owens-XKLZia7hPYI-unsplash.jpg', 'jakob-owens-XKLZia7hPYI-unsplash.jpg', 'sidekix-media-hmz7nC5mEu4-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This rustic and charming 3-bedroom farmhouse is situated on a sprawling acreage and features a cozy living room with a fireplace, a kitchen with a breakfast nook, and a large outdoor patio for entertaining. The property also includes a barn and is perfect for those who love the outdoors and country living.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:40:44', 'Success', 'Your Listing Is Live...'),
(176, 62, 'Stunning two-Bedroom Loft with Exposed Brick and High Ceilings', 'Flat', '2', 'Sell', 2, 2, 3, 1, 1, 1, 12, 1000000, '2199', '1001 Shree Devi Soc', 'Vadodara', 'Gujarat', 'greg-rivers-rChFUMwAe7E-unsplash.jpg', 'mostafa-safadel-cHjAxnJk_wQ-unsplash.jpg', 'eric-deschaintre-alSZkWagD54-unsplash.jpg', 'jonathan-borba-N3z-oIHLL3w-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>This stunning 2-bedroom loft is located in a historic building and features exposed brick, high ceilings, and large windows that flood the space with natural light. It also includes a gourmet kitchen, a dining area, and a rooftop terrace with city views.</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-17 12:43:57', 'Success', 'Your Listing Is Live...'),
(177, 62, 'This Is My First Listing ', 'House', '3', 'Rent', 4, 4, 4, 4, 3, 1, 1, 11223, '123', '49 md park socity simada gam surat3', 'Surat', 'Gujarat', 'spacejoy-vOa-PSimwg4-unsplash.jpg', 'francesca-tosolini-hCU4fimRW-c-unsplash.jpg', 'john-fornander-y3_AHHrxUBY-unsplash.jpg', 'josh-mclove-85kUBzS2V3g-unsplash.jpg', 'ebill.jpeg', 'tbill.jpeg', 'Active', 'Yes', '<p>qwert</p>', '<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Property Age : </span>10 Years</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Parking : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Maintanace : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Type : </span>Apartment</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Security : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Wifi Plan : </span>Yes</li>\r\n</ul>\r\n</div>\r\n<div class=\"col-md-4\">\r\n<ul>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">3rd Party : </span>No</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Elevator : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">CCTV : </span>Yes</li>\r\n<li class=\"mb-3\"><span class=\"text-black fw-bold\">Water Supply : </span>Ground Water / Tank</li>\r\n</ul>\r\n</div>', '2023-04-18 07:24:42', 'Pending', 'Your Listing Is Live...');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tblhouse`
--
ALTER TABLE `tblhouse`
  ADD PRIMARY KEY (`pid`);
ALTER TABLE `tblhouse` ADD FULLTEXT KEY `ptitle` (`ptitle`,`paddress`,`state`,`city`,`description`,`facilities`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tblhouse`
--
ALTER TABLE `tblhouse`
  MODIFY `pid` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=183;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
